/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as PassagersRouteImport } from './routes/passagers'
import { Route as ChauffeurRouteImport } from './routes/chauffeur'
import { Route as IndexRouteImport } from './routes/index'

const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagersRoute = PassagersRouteImport.update({
  id: '/passagers',
  path: '/passagers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeurRoute = ChauffeurRouteImport.update({
  id: '/chauffeur',
  path: '/chauffeur',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chauffeur': typeof ChauffeurRoute
  '/passagers': typeof PassagersRoute
  '/places': typeof PlacesRoute
  '/reservations': typeof ReservationsRoute
  '/resultats': typeof ResultatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chauffeur': typeof ChauffeurRoute
  '/passagers': typeof PassagersRoute
  '/places': typeof PlacesRoute
  '/reservations': typeof ReservationsRoute
  '/resultats': typeof ResultatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chauffeur': typeof ChauffeurRoute
  '/passagers': typeof PassagersRoute
  '/places': typeof PlacesRoute
  '/reservations': typeof ReservationsRoute
  '/resultats': typeof ResultatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chauffeur'
    | '/passagers'
    | '/places'
    | '/reservations'
    | '/resultats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chauffeur'
    | '/passagers'
    | '/places'
    | '/reservations'
    | '/resultats'
  id:
    | '__root__'
    | '/'
    | '/chauffeur'
    | '/passagers'
    | '/places'
    | '/reservations'
    | '/resultats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChauffeurRoute: typeof ChauffeurRoute
  PassagersRoute: typeof PassagersRoute
  PlacesRoute: typeof PlacesRoute
  ReservationsRoute: typeof ReservationsRoute
  ResultatsRoute: typeof ResultatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passagers': {
      id: '/passagers'
      path: '/passagers'
      fullPath: '/passagers'
      preLoaderRoute: typeof PassagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeur': {
      id: '/chauffeur'
      path: '/chauffeur'
      fullPath: '/chauffeur'
      preLoaderRoute: typeof ChauffeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChauffeurRoute: ChauffeurRoute,
  PassagersRoute: PassagersRoute,
  PlacesRoute: PlacesRoute,
  ReservationsRoute: ReservationsRoute,
  ResultatsRoute: ResultatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
